version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: recorp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: recorp2024
      POSTGRES_DB: recorp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: